# Generated by Django 3.1.5 on 2021-02-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creds_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cred',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creds_app.url'),
        ),
    ]
