# Generated by Django 3.1.5 on 2021-02-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creds_app', '0002_auto_20210205_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cred',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='cred',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creds_app.cred'),
        ),
    ]
