# Generated by Django 3.1.5 on 2021-02-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds_app', '0003_auto_20210205_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='cred',
        ),
        migrations.AddField(
            model_name='cred',
            name='url',
            field=models.ManyToManyField(to='creds_app.URL'),
        ),
    ]
